### ISSUE TITLE
Thank you for sharing this repo it's really meaningful. If possible can you release weight to infer. 

### ISSUE THREAD

**Issue by PhamLongVu** [CXH-Research/StainRestorer#1]

**Comment by PhamLongVu** [comment]
@xuhangc

**Comment by xuhangc** [comment]
Thank you for your interest in our work. We are currently finalizing our paper based on reviewer feedback. Additionally, this work is being extended for a journal submission. We plan to release the model weights after the conference.

**Comment by xuhangc** [comment]
@PhamLongVu Hi, the StainDoc checkpoint is now available [here](https://github.com/CXH-Research/StainRestorer/releases/tag/Weights). Please note that this is a retrained checkpoint, which may show slight metric variations compared to those reported in our paper. However, these differences are minimal and do not significantly impact performance.
